- name: play level variables
  hosts: local
  connection: local
  vars_files:
    course.yaml
  tasks:
  - name: Play level vars from seperate vars_files
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}"