- name: Prompt variables
  hosts: local
  connection: local
  vars_prompt:
   - name: username
     prompt: Please enter your username
     private: false

   - name: password
     prompt: Please enter password
     private: true

  tasks:
  - name: Varibles from prompts
    ansible.builtin.debug:
      msg: "username is: {{ username }}, password is: {{ password }}"
    