- name: ansible facts
  hosts: local
  connection: local
  tasks:
  - name: print facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: print if it is red hat or not
    ansible.builtin.debug:
      msg: "Yes it is Redhat"
    when: ansible_facts.os_family == "RedHat"
    