- name: Installing packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Installing packages
    ansible.builtin.packages:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - zip